name: codspeed

on:
  push:
    branches:
      - main
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

jobs:
  codspeed-profiling:
    name: codspeed profiling
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: install deps
        run: |
          uv venv --python 3.12
          uv sync --group testing --group testing-extra --extra email --frozen

      - name: Run CodSpeed benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: uv run pytest ./tests/benchmarks --codspeed
